version: "3"
services:
  collector:
    container_name: "pagespeedinsights-collector"
    image: node:18.12.1-alpine3.17
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    environment:
      - APIKey
      - PAGES
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker-compose/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
volumes:
  prometheus:
